django_aur/urls.py
from django.conf.urls import patterns, url
from django_aur import views

urlpatterns = patterns('',
   url(r'^$', views.aur, name='aur'),
)

django_publications/urls.py
from django.conf.urls import patterns, url
from django_publications import views

urlpatterns = patterns('',
   url(r'^(?P<slug>[-a-zA-Z0-9]+)/bibtex/$', views.bibtex, name='bibtex'),
)

eyolfson_website/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

from eyolfson_website import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.home, name='home'),
    url(r'^software/$', views.software, name='software'),
    url(r'^software/aur/', include('django_aur.urls')),
    url(r'^cv/$', views.cv, name='cv'),
    url(r'^about/$', views.about, name='about'),
    url(r'^teaching/', include('teaching.urls', namespace='teaching')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^publications/', include('django_publications.urls')),
)

if not settings.PRODUCTION:
    urlpatterns += patterns('django.views',
        url(r'^media/(?P<path>.*)', 'static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    )

teaching/urls.py
from django.conf.urls import patterns, url
from teaching.views import *

urlpatterns = patterns('',
   url(r'^$', home, name='home'),
)

blog/models.py
from datetime import datetime
from django.contrib.auth.models import User
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=80)
    slug = models.SlugField()
    text = models.TextField()
    date_time = models.DateTimeField(default=datetime.now)
 
    def __unicode__(self):
        return self.title

django_aur/models.py
from django.db import models

class Update(models.Model):
    package = models.SlugField(max_length=50, db_index=True)
    arch = models.CharField(max_length=50)
    version = models.CharField(max_length=50)
    time = models.DateTimeField(auto_now_add=True)

django_publications/models.py
from django.core.files.storage import default_storage
from django.db import models

PUBLICATIONS_DIR = 'publications'

def publication_path(instance, extra=''):
    path = '{}/{}{}.pdf'.format('publications', instance.slug, extra)
    default_storage.delete(path)
    return path

def publication_paper_path(instance, filename):
    return publication_path(instance)

def publication_slides_path(instance, filename):
    return publication_path(instance, '-slides')

class Publication(models.Model):
    slug = models.SlugField()
    display = models.TextField()
    paper = models.FileField(blank=True, upload_to=publication_paper_path)
    slides = models.FileField(blank=True, upload_to=publication_slides_path)
    pub_date = models.DateTimeField(blank=True, null=True)
    bibtex = models.TextField()

software/models.py
from django.db import models

class Project:
    slug = models.SlugField(max_length=50)
    url = models.URLField(max_length=200)
    description = models.TextField()

class AURProject:
    project = models.OneToOneField(Project)

class AURUpdate:
    package = models.SlugField(max_length=50)
    arch = models.CharField(max_length=50)
    version = models.CharField(max_length=50)
    updated = models.DateTimeField()

teaching/models.py
from django.core.files.storage import default_storage
from django.db import models

class Course(models.Model):
    slug = models.SlugField()
    abbreviation = models.CharField(max_length=10)
    title = models.CharField(max_length=80)

    def __unicode__(self):
        return u'{} ({})'.format(self.abbreviation, self.title)

class Offering(models.Model):
    def path(instance, filename):
        slug = instance.course.slug
        term = instance.term
        path = 'teaching/uwaterloo/{}/{}/{}'.format(slug, term, filename)
        default_storage.delete(path)
        return path

    course = models.ForeignKey(Course, related_name='offerings')
    term = models.PositiveSmallIntegerField()
    outline_file = models.FileField(blank=True, upload_to=path)
    midterm_file = models.FileField(blank=True, upload_to=path)
    final_file = models.FileField(blank=True, upload_to=path)

    def __unicode__(self):
        year = (1900 + self.term / 1000 * 100) + (self.term / 10  % 100)
        month = self.term % 10
        if month == 1:
            name = 'Winter'
        elif month == 5:
            name = 'Spring'
        elif month == 9:
            name = 'Fall'
        else:
            name = 'Unknown'
        return u'{}, {} {}'.format(unicode(self.course), name, year)

class Lecture(models.Model):
    def path(instance, filename):
        slug = instance.offering.course.slug
        term = instance.offering.term
        path = 'teaching/uwaterloo/{}/{}/lectures/{}'.format(slug, term,
                                                             filename)
        default_storage.delete(path)
        return path

    offering = models.ForeignKey(Offering, related_name='lectures')
    date = models.DateField()
    description = models.CharField(max_length=80)
    file = models.FileField(upload_to=path)

    def __unicode__(self):
        return self.description

    class Meta:
        ordering = ['date']

class Assignment(models.Model):
    def path(instance, filename):
        slug = instance.offering.course.slug
        term = instance.offering.term
        path = 'teaching/uwaterloo/{}/{}/assignments/{}'.format(slug, term,
                                                                filename)
        default_storage.delete(path)
        return path

    offering = models.ForeignKey(Offering, related_name='assignments')
    date = models.DateField()
    description = models.CharField(max_length=80)
    file = models.FileField(upload_to=path)

    def __unicode__(self):
        return self.description

    class Meta:
        ordering = ['date']

django_aur/views.py
from django.shortcuts import render
from django_aur.models import Update

def aur(request):
    return render(request, 'django_aur/aur.html',
                  {'updates': Update.objects.order_by('package', '-time')
                   .distinct('package')})

django_publications/views.py
from django.shortcuts import get_object_or_404, render

from django_publications.models import Publication

def bibtex(request, slug):
    publication = get_object_or_404(Publication, slug=slug)
    return render(request, 'publications/bibtex.html',
                  {'publication': publication})

eyolfson_website/views.py
from django.shortcuts import render

from blog.models import Post
from django_publications.models import Publication

def home(request):
    blog_posts = Post.objects.all()
    return render(request, 'home.html', {'blog_posts': blog_posts})

def software(request):
    return render(request, 'software.html')

def cv(request):
    context = {}
    try:
        p = Publication.objects.get(slug='masc-eyolfson')
        context['masc'] = p
    except Publication.DoesNotExist:
        pass
    context['publications'] = Publication.objects.exclude(slug='masc-eyolfson').order_by('-pub_date')
    return render(request, 'cv.html', context)

def about(request):
    return render(request, 'about.html')

teaching/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from teaching.models import Offering

def home(request):
    return render(request, 'teaching/home.html',
                  {'offerings': Offering.objects.all()})

templates/about.html
{% extends "base.html" %}

{% block title %} - About{% endblock %}
{% block nav-about %} class="active"{% endblock %}

{% block content %}
      <h1>About</h1>

      <h2>PGP Public Key</h2>

      <pre>-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.22 (GNU/Linux)

mQENBE/P4ikBCAC6srLXoLXCeGyCcAD3hE5py52QzxGeFPQUjozIts9ggFG4q4Yt
txx3pJADucyfe0qIrKWMRLoLatewRwvQLynKh6caJBs/gtu2aC0+svtnA6BFH7d2
80UZxEQkLAt9BpK5/3Vx5to0vMZ9xGuk417bnyjxskNo1QSg0EYpafUv9amc73bb
STZ+2e+idjDN3BhvuDqag9YKmPYsXagbV5SUe0fPhGz7rYguODt8z+Xrus/YEwsG
Ou76SNMobwQSmo1yE60MzuS5KrYJ3NHpM+gfyq1kr6AJ1k+Kx0fsj75tQEyXez5F
fHhsgPsa/XjGjK76znxIIa+I97qXcT4DK/gpABEBAAG0H0pvbiBFeW9sZnNvbiA8
am9uQGV5b2xmc29uLmNvbT6JATgEEwECACIFAk/P4ikCGwMGCwkIBwMCBhUIAgkK
CwQWAgMBAh4BAheAAAoJEL7iV2ci2XI/er8H/jk8v+g9SEeG1syEde5SJjNllkPV
9QKZ4wu0zT2pVf0cKSzNvaq8iiWpbxJOVXeI2EPAa8qdO6IVTxdLw++v94IGe+zp
ymqWci92MTE0cZBQJM8nL+oejixA39xGK3iyKtyY9yNKvOKl8NoYuxSJqGdl2Nht
6mbMe4B4e0HVEABaZv099q/FLzFwUvus5gA1v+LU0wXaNmqC66QOeSmfnZG7cmko
YHjkVMS/eX9QPKg2E5SLdIPS0iHbB3VG/wNM5nE+Ev1jbozBLqTGxvn6OMNf++zJ
eepxP5ZUKKFLRXFuWyUBo42EPDhCmHvEKHaAeIdZmgkkNKJRpzv2KKjJyBi5AQ0E
T8/iKQEIAM/DYEZlRyM/tyXIBoWG1FK6unsiO8YGtRKULd/BUv22YoiQ8LGcf8An
3BKYs1K4g3nzWrvejdeY0FXLlQiOxPJh+9PTr4Wbv2FfrvMgI9GrKDAl5kThuqWD
QP6iNXTvuqV7a9xPIXrby7fA/gAfV1i6khfN+hsYn1h02mSqGxx2m/XH+AYQecyo
y8hRt0pDyEZOmoa251VAnqouw6mVJtmyIwMkUQ7uOvAWOcQLZyfk4cKZfxyH+vt1
p03unAAyecW6hdJ4+Q/XLAnfMl59WAojr27EreY5IYJEUPGCFTrVEh7LZRL7GuQ3
UCy0uIrMVMgo+nWonGaJaGaeehf24UsAEQEAAYkBHwQYAQIACQUCT8/iKQIbDAAK
CRC+4ldnItlyP1asCACY0fK2POUsUlULYbxoYNz3H+rqHslPpvfN0/b5W+wDsz/h
89+N65QziMw9LHRxyxtiWK/36LnaICzWFcYPArsFVmkOnC4PG+MDzFRTY/O5rgwX
51b67oFanq79IzkLIoUKfIeQx+DrFF62HxYhe2t6N44hAnFjBHfDE4WZPTISbhmW
tE4vi0nSoK6HH8i3TSJa340r0Q/No2COraEtMr+CX1Dxe0nG90QdD28fH3L4lpZ5
TjJ6KYfx7v9TkbxWsC0s1Lav8NZMKvp519H267sH2tUrxFcFsN0ETdOkBzoo8d7i
cET7H/y0plPrUZURKBzw7Gv08mGNDrra/N6a1JaO
=qAvO
-----END PGP PUBLIC KEY BLOCK-----</pre>

      <p><a href="http://pgp.mit.edu:11371/pks/lookup?op=get&search=0xBEE2576722D9723F">MIT PGP Public Key Server</a></p>
{% endblock %}

templates/base.html
{% load staticfiles %}{% load url from future %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Eyolfson{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Jon Eyolfson's personal web page." />
    <link href="{% static "images/favicon.png" %}" rel="icon" type="image/png" />
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet" />
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">eyolfson.ca</a>
      </div>

      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <li{% block nav-software %}{% endblock %}><a href="{% url 'software' %}">Software</a></li>
          <li{% block nav-teaching %}{% endblock %}><a href="{% url 'teaching:home' %}">Teaching</a></li>
          <li{% block nav-cv %}{% endblock %}><a href="{% url 'cv' %}">CV</a></li>
          <li{% block nav-about %}{% endblock %}><a href="{% url 'about' %}">About</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
{% block content %}{% endblock %}
    </div>

    <script src="{% static "js/jquery.js" %}"></script>
    <script src="{% static "js/bootstrap.js" %}"></script>
  </body>
</html>

templates/blog/post_archive.html
{% extends "base_blog.html" %}

{% block content %}
<h1>Latest Blog Postings</h1>

{% for object in latest %}
<h2><a href="{{ object.get_absolute_url }}">{{ object.title|safe }}</a></h2>
<p class="indented">{{ object.body|safe }}</p>
<p>Posted by <strong>{{ object.author.first_name }}</strong> on {{ object.pub_date|date:"F j, Y" }}</p>
{% empty %}
<p class="stand-alone">There are no posts.</p>
{% endfor %}

{% if date_list %}
<div id="related-links">
  <div class="related-links-heading">Posts by Year</div>
  <ul>
    {% for date in date_list %}
    <li><a href="{% url blog_year date|date:"Y" %}">{{ date|date:"Y" }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endif %}
{% endblock %}

templates/blog/post_archive_day.html
{% extends "base_blog.html" %}

{% block content %}
<h1>{{ day|date:"F j, Y" }} Blog Postings</h1>

{% for object in object_list %}
<h2><a href="{{ object.get_absolute_url }}">{{ object.title|safe }}</a></h2>
<p class="indented">{{ object.body|safe }}</p>
<p>Posted by <strong>{{ object.author.first_name }}</strong> on {{ object.pub_date|date:"F j, Y" }}</p>
{% endfor %}
{% endblock %}

templates/blog/post_archive_month.html
{% extends "base_blog.html" %}

{% block content %}
<h1>{{ month|date:"F Y" }} Blog Postings</h1>

{% for object in object_list %}
<h2><a href="{{ object.get_absolute_url }}">{{ object.title|safe }}</a></h2>
<p class="indented">{{ object.body|safe }}</p>
<p>Posted by <strong>{{ object.author.first_name }}</strong> on {{ object.pub_date|date:"F j, Y" }}</p>
{% endfor %}
{% endblock %}

templates/blog/post_archive_year.html
{% extends "base_blog.html" %}

{% block content %}
<h1>{{ year }} Blog Postings</h1>

{% for object in object_list %}
<h2><a href="{{ object.get_absolute_url }}">{{ object.title|safe }}</a></h2>
<p>Posted by <strong>{{ object.author.first_name }}</strong> on {{ object.pub_date|date:"F j, Y" }}</p>
{% endfor %}

<div id="related-links">
  <div class="related-links-heading">Posts by Month</div>
  <ul>
    {% for date in date_list %}
    <li><a href="{% url blog_month date|date:"Y" date|date:"m" %}">{{ date|date:"F" }}</a></li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

templates/blog/post_detail.html
{% extends "base_blog.html" %}

{% block content %}
<h1>Blog Post</h1>

<h2><a href="{{ object.get_absolute_url }}">{{ object.title|safe }}</a></h2>
<p class="indented">{{ object.body|safe }}</p>
<p>Posted by <strong>{{ object.author.first_name }}</strong> on {{ object.pub_date|date:"F j, Y" }}</p>
{% endblock %}

templates/blog/post_list.html
{% extends "base_blog.html" %}

{% block content %}

{% for post in object_list %}
<p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
{% endfor %}

{% endblock %}

templates/cv.html
{% extends "base.html" %}

{% block title %} - CV{% endblock %}
{% block nav-cv %} class="active"{% endblock %}

{% block content %}
      <h1>CV</h1>

      <h2>Jon Eyolfson</h2>

      <h3>Education</h3>

      <ul class="list-unstyled">
        <li><strong>Ph.D., Computer Engineering</strong></li>
        <li>University of Waterloo, September 2011&ndash;Present</li>
        <li>Supervisor: Patrick Lam</li>
      </ul>

      <ul class="list-unstyled">
        <li><strong>M.A.Sc., Computer Engineering</strong></li>
        <li>University of Waterloo, September 2009&ndash;August 2011</li>
        <li>Supervisor: Patrick Lam</li>
        {% if masc %}
        <li>Thesis: {{ masc.display|safe }}</li>
        <li>
          <div class="well well-small">
            {% if masc.paper %}<a href="{{ masc.paper.url }}"><span class="glyphicon glyphicon-file"></span> Paper</a>{% endif %}
            {% if masc.slides %}<a href="{{ masc.slides.url }}"><span class="glyphicon glyphicon-file"></span> Slides</a>{% endif %}
            <a href="{% url 'bibtex' masc.slug %}"><span class="glyphicon glyphicon-pencil"></span> BibTeX</a>
          </div>
        </li>
        {% endif %}
      </ul>

      <ul class="list-unstyled">
        <li><strong>B.Sc., Computer Engineering (First Class Honours)</strong></li>
        <li>Queen's University, September 2005&ndash;April 2009</li>
      </ul>

      {% if publications %}
      <h3>Publications</h3>

      {% for publication in publications %}
      <ul class="list-unstyled">
        <li>{{ publication.display|safe }}</li>
        <li>
          <div class="well well-small">
            {% if publication.paper %}<a href="{{ publication.paper.url }}"><span class="glyphicon glyphicon-file"></span> Paper</a>{% endif %}
            {% if publication.slides %}<a href="{{ publication.slides.url }}"><span class="glyphicon glyphicon-file"></span> Slides</a>{% endif %}
            <a href="{% url 'bibtex' publication.slug %}"><span class="glyphicon glyphicon-pencil"></span> BibTeX</a>
          </div>
        </li>
      </ul>
      {% endfor %}
      {% endif %}

      <h3>Teaching</h3>

      <ul class="list-unstyled">
        <li><strong>Lab Instructor, ECE 351 (Compilers)</strong></li>
        <li>University of Waterloo, Spring 2013</li>
      </ul>

      <ul class="list-unstyled">
        <li><strong>Lab Instructor, ECE 351 (Compilers)</strong></li>
        <li>University of Waterloo, Winter 2013</li>
      </ul>

      <ul class="list-unstyled">
        <li><strong>Teaching Assistant, ECE 351 (Compilers)</strong></li>
        <li>University of Waterloo, Spring 2012</li>
      </ul>

      <ul class="list-unstyled">
        <li><strong>Instructor, ECE 459 (Programming for Performance)</strong></li>
        <li>University of Waterloo, Winter 2012</li>
      </ul>

      <ul class="list-unstyled">
        <li><strong>Teaching Assistant, ECE 459 (Programming for Performance)</strong></li>
        <li>University of Waterloo, Winter 2011</li>
      </ul>

      <ul class="list-unstyled">
        <li><strong>Teaching Assistant, ECE 251 (Programming Languages and Translators)</strong></li>
        <li>University of Waterloo, Fall 2010</li>
      </ul>

      <ul class="list-unstyled">
        <li><strong>Teaching Assistant, ECE 355 (Software Engineering)</strong></li>
        <li>University of Waterloo, Winter 2010</li>
      </ul>

      <h3>Awards</h3>
      <ul class="list-unstyled">
        <li><strong>NSERC Doctoral Postgraduate Scholarship</strong></li>
        <li>May 2013&ndash;April 2015</li>
      </ul>

      <ul class="list-unstyled">
        <li><strong>President's Graduate Scholarship, University of Waterloo</strong></li>
        <li>May 2013&ndash;April 2015</li>
      </ul>

      <ul class="list-unstyled">
        <li><strong>Amit & Meena Chakma Award for Exceptional Teaching by a Student, University of Waterloo</strong></li>
        <li>March 2013</li>
      </ul>

      <ul class="list-unstyled">
        <li><strong>Ontario Graduate Scholarship</strong></li>
        <li>May 2010&ndash;April 2011</li>
      </ul>

      <ul class="list-unstyled">
        <li><strong>President's Graduate Scholarship, University of Waterloo</strong></li>
        <li>May 2010&ndash;April 2011</li>
      </ul>
{% endblock %}

templates/django_aur/aur.html
{% extends "base.html" %}

{% block title %} - Software{% endblock %}
{% block nav-software %} class="active"{% endblock %}

{% block content %}
      <h1>aur-eyolfson</h1>

      <h2>Usage</h2>

      <p>If you would like to use my repository add the following to
      <code>/etc/pacman.conf</code>:</p>

      <pre>[eyolfson]
SigLevel = Optional
Server = http://aur.eyolfson.ca/$arch</pre>

  {% if updates %}
      <h2>Updates</h2>

      <table class="table table-striped">
        <thead>
          <tr>
            <th>Package</th>
            <th>Arch</th>
            <th>Version</th>
            <th>Time</th>
          </tr>
        </thead>
        <tbody>
      {% for update in updates %}
          <tr>
            <td>{{ update.package }}</td>
            <td>{{ update.arch }}</td>
            <td>{{ update.version }}</td>
            <td>{{ update.time }}</td>
          </tr>
      {% endfor %}
        </tbody>
      </table>
  {% endif %}
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block content %}
      <h1>Home</h1>

      <p>This is my personal web page and is a work in progress. Currently it
      contains my CV and that's about it. Soon it should contain something more
      interesting.</p>

      <h2>Blog</h2>
      
  {% for post in blog_posts %}
      <h3>{{ post.title }}</h3>

      <p><strong>Posted: {{ post.date_time }}</strong></p>
      
      {{ post.text|safe }}
  {% endfor %}
{% endblock %}

templates/publications/bibtex.html
{% extends "base.html" %}

{% block title %} - CV{% endblock %}
{% block nav-cv %} class="active"{% endblock %}

{% block content %}
      <h1>BibTeX</h1>

      <pre>{{ publication.bibtex|safe }}</pre>
{% endblock %}

templates/software.html
{% extends "base.html" %}

{% block title %} - Software{% endblock %}
{% block nav-software %} class="active"{% endblock %}

{% block content %}
      <h1>Software</h1>

      <dl>
        <dt><a href="{% url 'aur' %}">aur-eyolfson</a></dt>
        <dd>This is my custom ArchLinux package repository for my AUR packages.</dd>
      </dl>
{% endblock %}

templates/teaching/home.html
{% extends "base.html" %}

{% block title %} - Teaching{% endblock %}
{% block nav-teaching %} class="active"{% endblock %}

{% block content %}
<h1>Teaching</h1>

{% for offering in offerings %}
<h2>{{ offering }}</h2>

{% if offering.outline_file or offering.midterm_file or offering.final_file %}
<h3>Materials</h3>

<ul class="list-unstyled">
  {% if offering.outline_file %}
  <li><a href="{{ offering.outline_file.url }}">Outline</a></li>
  {% endif %}
  {% if offering.midterm_file %}
  <li><a href="{{ offering.midterm_file.url }}">Midterm</a></li>
  {% endif %}
  {% if offering.final_file %}
  <li><a href="{{ offering.final_file.url }}">Final</a></li>
  {% endif %}
</ul>
{% endif %}

{% if offering.lectures.exists %}
<h3>Lectures</h3>

<ul class="list-unstyled">
  {% for lecture in offering.lectures.all %}
  <li><a href="{{ lecture.file.url }}">{{ lecture }}</a></li>
  {% endfor %}
</ul>
{% endif %}

{% if offering.assignments.exists %}
<h3>Assignments</h3>

<ul class="list-unstyled">
  {% for assignment in offering.assignments.all %}
  <li><a href="{{ assignment.file.url }}">{{ assignment }}</a></li>
  {% endfor %}
</ul>
{% endif %}
{% endfor %}
{% endblock %}